---
- name: Configure development environment
  hosts: localhost
  connection: local
  tasks:
    - name: Administrative setup actions
      become: true
      block: 
        - name: Add Azure CLI key
          apt_key:
            id: 417A0893
            keyserver: packages.microsoft.com
        - name: Add Azure CLI to sources list
          apt_repository:
            repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main

        - name: add .netcore key
          apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            state: present
        - name: Add .net to sources list
          apt_repository:
            repo: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic main

        - name: Add Node key
          apt_key:
            url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        - name: Add Node to sources list
          apt_repository:
            repo: '{{item}}'
            filename: nodesource
          with_items:
            - deb https://deb.nodesource.com/node_12.x bionic main
            - deb-src https://deb.nodesource.com/node_12.x bionic main

        - name: Add neofetch repository
          apt_repository:
            repo: ppa:dawidd0811/neofetch

        - name: Update apt-cache
          apt:
            update_cache: yes
            cache_valid_time: 3600

        - name: Install packages
          apt:
            name: '{{item}}'
          with_items:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
            - jq
            - azure-cli
            - nodejs
            - git
            - zsh
            - neofetch
            - build-essential
            - python-pip
            - tmux
            - vim
            - python-pygments
            - cmake
            - zip
            - unzip
            - fonts-powerline

        - name: Upgrade all packages
          apt:
            upgrade: yes

        - name: Install argcomplete for Azure CLI
          pip:
            name: argcomplete

        - name: Download & extract Go
          unarchive:
            src: https://storage.googleapis.com/golang/go1.12.13.linux-amd64.tar.gz
            dest: /usr/local
            remote_src: yes
            creates: /usr/local/go/bin/go

        - name: Download kubectl
          block:
            - name: Create staging directory for Helkubectlm
              file:
                path: /usr/local/src/kubectl
                state: directory
            - name: Download and extract kubectl
              unarchive:
                src: https://dl.k8s.io/v1.14.9/kubernetes-client-linux-amd64.tar.gz
                dest: /usr/local/src/kubectl
                remote_src: yes
                creates: /usr/local/src/kubectl/kubernetes/client/bin/kubectl
            - name: Copy kubectl to /usr/local/bin
              copy:
                src: /usr/local/src/kubectl/kubernetes/client/bin/kubectl
                dest: /usr/local/bin/kubectl
                remote_src: yes
                force: no
                mode: 0755
        
        - name: Install kubectx
          block:
            - name: Create staging directory for kubectx
              file:
                path: /usr/local/src/kubectx
                state: directory
            - name: Download and extract kubectx
              unarchive:
                src: https://github.com/ahmetb/kubectx/archive/v0.7.1.tar.gz
                dest: /usr/local/src/kubectx
                remote_src: yes
                extra_opts: ['--strip-components=1']
            - name: Copy tools to /usr/local/bin
              file:
                state: link
                src: '/usr/local/src/kubectx/{{item}}'
                dest: '/usr/local/bin/{{item}}'
                remote_src: yes
                mode: 0755
              with_items:
                - kubectx
                - kubens
            - name: Link completion scripts
              file:
                state: link
                src: '/usr/local/src/kubectx/completion/{{item.src}}'
                dest: '/usr/share/zsh/functions/Completion/{{item.dest}}'
              with_items:
                - { src: 'kubectx.zsh', dest: '_kubectx' }
                - { src: 'kubens.zsh', dest: '_kubens' }

        - name: Install Helm
          block:
            - name: Create staging directory for Helm
              file:
                path: /usr/local/src/helm
                state: directory
            - name: Download and extract Helm
              unarchive:
                src: https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
                dest: /usr/local/src/helm
                remote_src: yes
                creates: /usr/local/src/helm/linux-amd64/helm
            - name: Copy Helm to /usr/local/bin
              copy:
                src: /usr/local/src/helm/linux-amd64/helm
                dest: /usr/local/bin/helm
                remote_src: yes
                force: no
                mode: 0755

        #if fails to set defualt shell run 'chsh -s $(which zsh)'
        - name: Set Zsh as the default shell
          user:
            name: jstur
            shell: /bin/zsh
            append: yes

    - name: Cloning oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: ~/.oh-my-zsh

    - name: Set up devbox repo
      block:
        - name: Clone jsturtevant/devbox
          when: devbox_dev is undefined
          git:
            repo: https://github.com/jsturtevant/devbox
            dest: ~/.devbox
        - name: Use ssh when pushing changes to origin
          shell: |
            if ! git remote -v | grep -q git@github.com; then
              git remote set-url --push origin git@github.com:jsturtevant/devbox.git
            fi
          changed_when: false
          args:
            chdir: ~/.devbox

    - name: Tmux setup
      block:
        - name: Create ~/.tmux/plugins
          file:
            path: ~/.tmux/plugins
            state: directory
        - name: Clone tmux plugin manager
          git:
            repo: https://github.com/tmux-plugins/tpm
            dest: ~/.tmux/plugins/tpm

    - name: Vim setup
      block:
        - name: Create ~/.vim/autoload
          file:
            path: ~/.vim/autoload
            state: directory
        - name: Clone plug.vim
          get_url:
            url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            dest: ~/.vim/autoload/plug.vim
          #- name: Install vim plugins
          #command: vim +PlugInstall +qall
          #changed_when: false

    - name: Link dotfiles
      file:
        state: link
        src: '~/.devbox/dotfiles/{{item}}'
        dest: '~/{{item}}'
      with_items:
        - .gitconfig

    - name: Link Linux-specific dotfiles
      file:
        state: link
        src: '~/.devbox/linux/{{item}}'
        dest: '~/{{item}}'
      with_items:
        - .dircolors
        - .tmux.conf
        - .vimrc
        - .zsh-custom
        - .zshrc

    - name: Update ownership of home folder
      file:
        dest: ~/
        state: directory
        owner: jstur
        group: jstur
        recurse: yes
